### ISSUE TITLE
Invalid credentialsRegExp

### ISSUE THREAD

**Issue by davidsykes** [jshttp/basic-auth#16]
I think
/^ *(?:[Bb][Aa][Ss][Ii][Cc]) +([A-Za-z0-9\-\._~\+\/]+=*) *$/
should be
/^ *(?:[Bb][Aa][Ss][Ii][Cc]) +([A-Za-z0-9\-\._~\+\/]+=.*) *$/

The final =* is matching multiple '=' rather than the password value

**Comment by davidsykes** [comment]
Apologies, I totally missed the base 64 bits

**Comment by dougwilson** [comment]
No problem. What was the underlying issue that even made you look into the RegExp?

**Comment by davidsykes** [comment]
I got a bit confused by the example in readme.md

'res.setHeader('WWW-Authenticate', 'Basic realm="example"')'

This didn't work, so I checked the code. The actual header seems to be
'authorization', and then the regex would only match 'Basic
realm="example"' if you applied my correction.

However I later got to the base64 conversion and the penny dropped. I can
now use the code unmodified.

I suspect the documentation is fine and that I have misunderstood
something, but I'm glad I looked at the code, I understand it a lot better
now.

Thanks Douglas



On 25 June 2015 at 16:03, Douglas Christopher Wilson <
notifications@github.com> wrote:

> No problem. What was the underlying issue that even made you look into the
> RegExp?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jshttp/basic-auth/issues/16#issuecomment-115286025>.
>



-- 
David

**Comment by dougwilson** [comment]
No problem :) And let me know if we can make the example clearer, haha. The example for this module is to call `var credentials = auth(req)`; the rest is so you can actually run the example, and if you return a 401, you MUST set the `WWW-Authenticate` header, which is why we do it in the example, otherwise it would not work as a complete runnable example.
