### ISSUE TITLE
Add support for es6 default import

### ISSUE THREAD

**Issue by CaselIT** [jshttp/basic-auth#25]
I was wondering if it would be possible to add `module.exports.default = auth;` to add support to the default es6 style import `import auth from "basic-auth"`

Thanks

**Comment by blakeembrey** [comment]
For background, see https://github.com/types/npm-basic-auth/pull/1 and https://github.com/typings/discussions/issues/32. Deferring to @dougwilson's opinion as mine has been stated elsewhere, but I can elaborate if needed.

**Comment by CaselIT** [comment]
After further discussion with @blakeembrey (in https://github.com/types/npm-basic-auth/pull/1) I came to the conclusion that while useful, still to many variables on the implementation of es6 in nodejs are left open, that could require the removal of the default export.
