### ISSUE TITLE
Add support for URL encoding

### ISSUE THREAD

**Issue by opatut** [jshttp/basic-auth#26]
See [Wikipedia: Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding)

Basically I'd like the `http://user@pass:domain.tld` format to be parsed as well, not only the auth header.

**Comment by dougwilson** [comment]
I am able to use that just fine using the example in the README: https://github.com/jshttp/basic-auth#with-vanilla-nodejs-http-server

When I make a request to `http://user@pass:localhost:3000/` I get `Access granted`.

**Comment by dougwilson** [comment]
![image](https://cloud.githubusercontent.com/assets/67512/19795151/385ade3a-9ca7-11e6-8e31-8f173b2ad73c.png)

**Comment by opatut** [comment]
Sorry, I looked at the code and did not see any URL parsing. However that was a misunderstanding of the actual "URL encoding" method: it's a browser feature, not a HTTP standard, and the credentials are actually converted to a base64 encoded Authorization header.

Nevermind then, and thanks for clearing this up. Sorry again.
