### ISSUE TITLE
Use constant-time comparison to prevent timing attacks.

### ISSUE THREAD

**Issue by autopulated** [jshttp/basic-auth#28]
Currently the examples suggest comparing the supplied username and password against the true values with `===`, which will take a different amount of time based on how far along the string the difference is, potentially allowing an attacker to reverse engineer the username and password.

It would be better to either hash the supplied password and true password and compare the hashes, or use [crypto.timinSafeEqual](https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b) for comparison.

**Comment by dougwilson** [comment]
Examples are just simple examples to show how to use this module. Users should understand what they need to do.

**Comment by almacha** [comment]
I can't believe you consider this problem does not matter at all. The reference example shown on home page contains a security flaw, there should at least be a warning that this way of doing the comparison is not safe for production use. Developers would expect the reference example to show a proper way to use the module.

**Comment by dougwilson** [comment]
I'll delete the example from the README 👍

**Comment by dougwilson** [comment]
> I can't believe you consider this problem does not matter at all.

I never said this and it was very rude to imply that this was my attitude. Please refrain from using my modules.
