### ISSUE TITLE
Is the example w/ express? and example w/ express routes? (eom)

### ISSUE THREAD

**Issue by cekvenich** [jshttp/basic-auth#29]
thx for any help.

**Comment by blakeembrey** [comment]
The examples are using the http module built in node, described https://github.com/jshttp/basic-auth#with-vanilla-nodejs-http-server. If you want something that works as middleware, try https://github.com/expressjs/basic-auth-connect.

**Comment by dougwilson** [comment]
Since Express is just a sugar layer on top of Node.js server, the example from the README is easily switched to Express. For example:
```js
var auth = require('basic-auth')
var express = require('express')

// Create app
var app = express()

app.use(function (req, res, next) {
  var credentials = auth(req)

  if (!credentials || credentials.name !== 'john' || credentials.pass !== 'secret') {
    res.status(401)
    res.header('WWW-Authenticate', 'Basic realm="example"')
    res.send('Access denied')
  } else {
    next()
  }
})

// More routes here

// Listen
app.listen(3000)
```

**Comment by jesgundy** [comment]
Super helpful answer - would consider putting in the Readme, fwiw.

**Comment by dougwilson** [comment]
Since this is bot an express specific module, I would rather not, as otherwise the README will turn into a giant list of examples for every conceivable framework out there.

**Comment by jesgundy** [comment]
Fair point. Cheers.
