### ISSUE TITLE
Questions about realms

### ISSUE THREAD

**Issue by adam-beck** [jshttp/basic-auth#30]
I understand what a realm is (I think) and in the example I see one is added to the header: `res.setHeader('WWW-Authenticate', 'Basic realm="example"')`. Is there any information on how this works or how to define different realms in node.js/express servers?

**Comment by dougwilson** [comment]
That is probably a bit beyond this module, which all it does it parse a header with basic auth credentials back to username / password. The most I can really say is already in the README.

**Comment by dougwilson** [comment]
From reading https://tools.ietf.org/html/rfc2617 and various other sites, the realm is for the pages which share the same credentials. The way you specify it is to send a `WWW-Authenticate` headers with the realm named. That's pretty much what I got from reading around.

**Comment by adam-beck** [comment]
Thank you for your time addressing this
