### ISSUE TITLE
Passing basic http credentials in URI

### ISSUE THREAD

**Issue by GodsBreath** [jshttp/basic-auth#35]
This isn't so much an issue as it is a feature request. My understanding is that the basic HTTP authentication scheme allows for usernames and passwords to be sent in the URI like so:

`https://username:password@host.example.com`

Was it a deliberate decision to leave this feature out? It can be very helpful when trying to test authentication, because you can send requests through your browser and see the results without having to modify headers.

**Comment by GodsBreath** [comment]
Sorry, this is the wrong github repository. I meant to post this in the express-basic-auth repository. Please ignore.

**Comment by dougwilson** [comment]
You can always close the issue and I don't want to just close it on you. Are you asking for the issue to be closed or something else?

**Comment by GodsBreath** [comment]
It can be closed. Upon doing some more research, I have discovered that this method of passing basic HTTP credentials is falling out of favor with the major browsers and support has been dropped for some time. Chrome 56, which is what I'm currently using, is stripping out the credentials before it even sends the requests, so it wouldn't do any good to add support in express-basic-auth.
