### ISSUE TITLE
Header is case sensitive

### ISSUE THREAD

**Issue by Siilwyn** [jshttp/basic-auth#43]
While debugging some code running in a lambda environment I figured that `basic-auth` is not working since `Authorization` is used with a capital 'A'.

Instead of retrieving the value with `headers.authorization` something like this should work:
```js
headers [Object.keys(headers).find(key => key.toLowerCase() === 'authorization')]
```

This would comply with the spec, headers should not be case sensitive: https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

**Comment by Siilwyn** [comment]
@dougwilson ah that makes sense, maybe link to it from the readme?

**Comment by dougwilson** [comment]
Absolutely! Looks like you already opened a pull request.

**Comment by hoang-innomizetech** [comment]
I am facing this issue too. In the event.headers, some our custom headers are converted to lowercase. Such as on the FE we are sending X-Header-A, but on the event object, we received x-header-a as the header key
