### ISSUE TITLE
iOS:12.0.1

### ISSUE THREAD

**Issue by weider69** [jshttp/basic-auth#45]
iOS:12.0.1
64G black xs max
move slider -> nothing happened

same code works fine on my 6s plus(12.1.1)

__Originally posted by @TozyZuo in https://github.com/anthonya1999/GoodNight/issues/123__

**Comment by dougwilson** [comment]
Hi @weider69 , I think you may have posted this in the wrong repository. If not, please expand on your specific usage of this module and provide more details and we can re-open.
