### ISSUE TITLE
How do i remove the pop up and make a custom html login page with basic-auth?

### ISSUE THREAD

**Issue by alexia-rose** [jshttp/basic-auth#49]
![127760008-e9ee6a18-fcd6-4cb5-8bf5-e29217760ff5](https://user-images.githubusercontent.com/88448176/130222372-1700e163-0d2f-4342-bc8c-5af53260f30e.png)
i want to remove this pop-up and make a custom html page with this

**Comment by dougwilson** [comment]
No browser I am aware of will let you do that. But you would need to consult the documentation for the web browser you are trying to design for to know for sure.
